# Generated by Django 4.1.3 on 2023-02-09 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='iamges'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='timeline_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
